version: '3.8'
services:
  db_ldg:
    image: postgres:15
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data_ldg:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    restart: always
volumes:
  postgres-data_ldg:
      