services:
  postgres_ldg:
    image: postgres:15
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=postgres
    volumes:
      - postgres_volume_ldg:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  postgres_volume_ldg:
    name: postgres_volume_ldg
